# Generated by Django 5.1.4 on 2025-01-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("disease_id", models.AutoField(primary_key=True, serialize=False)),
                ("disease_name", models.CharField(max_length=100)),
            ],
        ),
    ]
