# Generated by Django 5.1.4 on 2025-01-09 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "departments",
                    models.ManyToManyField(
                        related_name="administrators", to="departments.department"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrators",
                        to="hospitals.hospital",
                    ),
                ),
            ],
        ),
    ]
