# Generated by Django 5.1.4 on 2025-01-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                ("medicine_name", models.CharField(max_length=100)),
            ],
        ),
    ]
