# Generated by Django 5.1.4 on 2025-01-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("Hospital_id", models.AutoField(primary_key=True, serialize=False)),
                ("Hospital_name", models.CharField(max_length=100)),
                ("Hospital_address", models.TextField()),
            ],
        ),
    ]
