# Generated by Django 5.1.4 on 2025-01-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("diseases", "0001_initial"),
        ("doctors", "0001_initial"),
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discharged", "Discharged"),
                            ("admitted", "Admitted"),
                            ("waiting", "Waiting"),
                        ],
                        max_length=10,
                    ),
                ),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diseases.disease",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.medicine",
                    ),
                ),
            ],
        ),
    ]
