# Generated by Django 5.1.4 on 2025-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(default="shetty123@gmail.com", max_length=254),
        ),
    ]
