# Generated by Django 5.1.4 on 2025-01-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
